# generated code By QT Designer
from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime



class SmartHouse(object):


    def setupUiLS(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(749, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(749, 391))
        Form.setMaximumSize(QtCore.QSize(749, 391))
        Form.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(False)
        Form.setTabletTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(True)
        Form.setAutoFillBackground(False)
        self.Lockscreen_Frame = QtWidgets.QFrame(Form)
        self.Lockscreen_Frame.setGeometry(QtCore.QRect(0, 0, 749, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lockscreen_Frame.sizePolicy().hasHeightForWidth())
        self.Lockscreen_Frame.setSizePolicy(sizePolicy)
        self.Lockscreen_Frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Lockscreen_Frame.setMouseTracking(True)
        self.Lockscreen_Frame.setAutoFillBackground(False)
        self.Lockscreen_Frame.setStyleSheet("background-color: rgb(16, 128, 128);")
        self.Lockscreen_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Lockscreen_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Lockscreen_Frame.setLineWidth(0)
        self.Lockscreen_Frame.setObjectName("Lockscreen_Frame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Lockscreen_Frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(250, 180, 241, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.weekday_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.weekday_label.setFont(font)
        self.weekday_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.weekday_label.setObjectName("weekday_label")
        self.horizontalLayout_2.addWidget(self.weekday_label)
        self.month_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.month_label.setFont(font)
        self.month_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.month_label.setObjectName("month_label")
        self.horizontalLayout_2.addWidget(self.month_label)
        self.day_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.day_label.setFont(font)
        self.day_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.day_label.setObjectName("day_label")
        self.horizontalLayout_2.addWidget(self.day_label)
        self.date_separator_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.date_separator_label.setFont(font)
        self.date_separator_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.date_separator_label.setObjectName("date_separator_label")
        self.horizontalLayout_2.addWidget(self.date_separator_label)
        self.year_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.year_label.setFont(font)
        self.year_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.year_label.setObjectName("year_label")
        self.horizontalLayout_2.addWidget(self.year_label)
        self.time_separator = QtWidgets.QLabel(self.Lockscreen_Frame)
        self.time_separator.setGeometry(QtCore.QRect(310, 60, 117, 119))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.time_separator.setFont(font)
        self.time_separator.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.time_separator.setTextFormat(QtCore.Qt.AutoText)
        self.time_separator.setScaledContents(True)
        self.time_separator.setAlignment(QtCore.Qt.AlignCenter)
        self.time_separator.setWordWrap(True)
        self.time_separator.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.time_separator.setObjectName("time_separator")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Lockscreen_Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 60, 281, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hour_label = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.hour_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hour_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.hour_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hour_label.setDigitCount(2)
        self.hour_label.setProperty("intValue", 88)
        self.hour_label.setObjectName("hour_label")
        self.horizontalLayout.addWidget(self.hour_label)
        self.minutes_label = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.minutes_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.minutes_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.minutes_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minutes_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minutes_label.setDigitCount(2)
        self.minutes_label.setProperty("intValue", 88)
        self.minutes_label.setObjectName("minutes_label")
        self.horizontalLayout.addWidget(self.minutes_label)
        self.am_pm_label = QtWidgets.QLabel(self.Lockscreen_Frame)
        self.am_pm_label.setGeometry(QtCore.QRect(510, 150, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.am_pm_label.setFont(font)
        self.am_pm_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.am_pm_label.setObjectName("am_pm_label")
        self.homescreen_temperature_label = QtWidgets.QLabel(self.Lockscreen_Frame)
        self.homescreen_temperature_label.setGeometry(QtCore.QRect(680, 0, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.homescreen_temperature_label.setFont(font)
        self.homescreen_temperature_label.setObjectName("homescreen_temperature_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Lockscreen_Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(248, 220, 241, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.keypad_button_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_5.setObjectName("keypad_button_5")
        self.gridLayout.addWidget(self.keypad_button_5, 2, 1, 1, 1)
        self.pswrd_processbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.pswrd_processbar.setMaximum(4)
        self.pswrd_processbar.setProperty("value", 0)
        self.pswrd_processbar.setObjectName("pswrd_processbar")
        self.gridLayout.addWidget(self.pswrd_processbar, 0, 0, 1, 3)
        self.keypad_button_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_2.setObjectName("keypad_button_2")
        self.gridLayout.addWidget(self.keypad_button_2, 1, 1, 1, 1)
        self.keypad_button_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_3.setObjectName("keypad_button_3")
        self.gridLayout.addWidget(self.keypad_button_3, 1, 2, 1, 1)
        self.keypad_button_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_8.setObjectName("keypad_button_8")
        self.gridLayout.addWidget(self.keypad_button_8, 3, 1, 1, 1)
        self.keypad_button_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_1.setObjectName("keypad_button_1")
        self.gridLayout.addWidget(self.keypad_button_1, 1, 0, 1, 1)
        self.keypad_button_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_6.setObjectName("keypad_button_6")
        self.gridLayout.addWidget(self.keypad_button_6, 2, 2, 1, 1)
        self.keypad_button_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_7.setObjectName("keypad_button_7")
        self.gridLayout.addWidget(self.keypad_button_7, 3, 0, 1, 1)
        self.keypad_button_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_4.setObjectName("keypad_button_4")
        self.gridLayout.addWidget(self.keypad_button_4, 2, 0, 1, 1)
        self.keypad_button_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_9.setAutoFillBackground(False)
        self.keypad_button_9.setObjectName("keypad_button_9")
        self.gridLayout.addWidget(self.keypad_button_9, 3, 2, 1, 1)
        self.keypad_button_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_0.setObjectName("keypad_button_0")
        self.gridLayout.addWidget(self.keypad_button_0, 4, 1, 1, 1)

        self.lock_button = QtWidgets.QPushButton(self.Lockscreen_Frame)
        self.lock_button.setGeometry(QtCore.QRect(150, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lock_button.setFont(font)
        self.lock_button.setObjectName("lock_button")

        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.am_pm_label.raise_()
        self.homescreen_temperature_label.raise_()
        self.gridLayoutWidget.raise_()
        self.time_separator.raise_()

        self.retranslateUiLS(Form)

        self.lock_button.pressed.connect(Form.close)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUiLS(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LockScreen"))
        self.weekday_label.setText(_translate("Form", "Weekday"))
        self.month_label.setText(_translate("Form", "Month"))
        self.day_label.setText(_translate("Form", "Day"))
        self.date_separator_label.setText(_translate("Form", ","))
        self.year_label.setText(_translate("Form", "Year"))
        self.time_separator.setText(_translate("Form", ":"))
        self.am_pm_label.setText(_translate("Form", "AM"))
        self.homescreen_temperature_label.setText(_translate("Form", " 23 ºC"))
        self.keypad_button_5.setText(_translate("Form", "5"))
        self.keypad_button_2.setText(_translate("Form", "2"))
        self.keypad_button_3.setText(_translate("Form", "3"))
        self.keypad_button_8.setText(_translate("Form", "8"))
        self.keypad_button_1.setText(_translate("Form", "1"))
        self.keypad_button_6.setText(_translate("Form", "6"))
        self.keypad_button_7.setText(_translate("Form", "7"))
        self.keypad_button_4.setText(_translate("Form", "4"))
        self.keypad_button_9.setText(_translate("Form", "9"))
        self.keypad_button_0.setText(_translate("Form", "0"))
        self.lock_button.setText(_translate("Form", "🔒"))

    def setupUiHS(self, Homescreen, setupUiAm, setupUiSec, setupUiSet):

        weekday = datetime.now().strftime("%a")
        day = datetime.now().strftime("%d")
        month = datetime.now().strftime("%B")
        year = datetime.now().strftime("%Y")
        hour = datetime.now().strftime("%I")
        minutes = datetime.now().strftime("%M")
        am_pm = datetime.now().strftime("%p")

        Homescreen.setObjectName("Homescreen")
        Homescreen.setWindowModality(QtCore.Qt.WindowModal)
        Homescreen.resize(749, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Homescreen.sizePolicy().hasHeightForWidth())
        Homescreen.setSizePolicy(sizePolicy)
        Homescreen.setSizeIncrement(QtCore.QSize(1, 1))
        Homescreen.setAcceptDrops(True)
        Homescreen.setAutoFillBackground(True)
        Homescreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Homescreen)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_Frame.setGeometry(QtCore.QRect(0, 0, 749, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_Frame.sizePolicy().hasHeightForWidth())
        self.Main_Frame.setSizePolicy(sizePolicy)
        self.Main_Frame.setAutoFillBackground(False)
        self.Main_Frame.setStyleSheet("background-color: rgb(16, 128, 128);")
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Main_Frame.setLineWidth(0)
        self.Main_Frame.setObjectName("Main_Frame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Main_Frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(250, 180, 241, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.weekday_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.weekday_label.setFont(font)
        self.weekday_label.setObjectName("weekday_label")
        self.horizontalLayout_2.addWidget(self.weekday_label)
        self.month_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.month_label.setFont(font)
        self.month_label.setObjectName("month_label")
        self.horizontalLayout_2.addWidget(self.month_label)
        self.day_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.day_label.setFont(font)
        self.day_label.setObjectName("day_label")
        self.horizontalLayout_2.addWidget(self.day_label)
        self.date_separator_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.date_separator_label.setFont(font)
        self.date_separator_label.setObjectName("date_separator_label")
        self.horizontalLayout_2.addWidget(self.date_separator_label)
        self.year_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.year_label.setFont(font)
        self.year_label.setObjectName("year_label")
        self.horizontalLayout_2.addWidget(self.year_label)
        self.time_separator = QtWidgets.QLabel(self.Main_Frame)
        self.time_separator.setGeometry(QtCore.QRect(310, 60, 117, 119))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.time_separator.setFont(font)
        self.time_separator.setTextFormat(QtCore.Qt.AutoText)
        self.time_separator.setScaledContents(True)
        self.time_separator.setAlignment(QtCore.Qt.AlignCenter)
        self.time_separator.setWordWrap(True)
        self.time_separator.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.time_separator.setObjectName("time_separator")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Main_Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 60, 281, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hour_label = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.hour_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.hour_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hour_label.setDigitCount(2)
        self.hour_label.setProperty("intValue", datetime.now().strftime("%I"))
        self.hour_label.setObjectName("hour_label")
        self.horizontalLayout.addWidget(self.hour_label)
        self.minutes_label = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.minutes_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.minutes_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minutes_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minutes_label.setDigitCount(2)
        self.minutes_label.setProperty("intValue", datetime.now().strftime("%M"))
        self.minutes_label.setObjectName("minutes_label")
        self.horizontalLayout.addWidget(self.minutes_label)
        self.am_pm_label = QtWidgets.QLabel(self.Main_Frame)
        self.am_pm_label.setGeometry(QtCore.QRect(510, 150, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.am_pm_label.setFont(font)
        self.am_pm_label.setObjectName("am_pm_label")
        self.homescreen_temperature_label = QtWidgets.QLabel(self.Main_Frame)
        self.homescreen_temperature_label.setGeometry(QtCore.QRect(680, 0, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.homescreen_temperature_label.setFont(font)
        self.homescreen_temperature_label.setObjectName("homescreen_temperature_label")
        self.settings_button = QtWidgets.QPushButton(self.Main_Frame)
        self.settings_button.setGeometry(QtCore.QRect(0, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.settings_button.setFont(font)
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Main_Frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(130, 240, 491, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ambient_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ambient_button.setObjectName("ambient_button")
        self.horizontalLayout_4.addWidget(self.ambient_button)
        self.security_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.security_button.setObjectName("security_button")
        self.horizontalLayout_4.addWidget(self.security_button)
        self.lock_button = QtWidgets.QPushButton(self.Main_Frame)
        self.lock_button.setGeometry(QtCore.QRect(150, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lock_button.setFont(font)
        self.lock_button.setObjectName("lock_button")
        Homescreen.setCentralWidget(self.centralwidget)

        self.retranslateUiHS(Homescreen, setupUiAm, setupUiSec, setupUiSet)

        # buttons leading to Ambient, Security and settings
        self.ambient_button.pressed.connect(setupUiAm.show)
        self.ambient_button.pressed.connect(Homescreen.close)
        self.security_button.pressed.connect(setupUiSec.show)
        self.security_button.pressed.connect(Homescreen.close)
        self.settings_button.pressed.connect(setupUiSet.show)
        self.settings_button.pressed.connect(Homescreen.close)
        self.lock_button.pressed.connect(Homescreen.close)

        QtCore.QMetaObject.connectSlotsByName(Homescreen)

    def retranslateUiHS(self, Homescreen, setupUiAm, setupUiSec, setupUiSet):

        _translate = QtCore.QCoreApplication.translate
        Homescreen.setWindowTitle(_translate("Homescreen", "Home"))
        self.weekday_label.setText(_translate("Homescreen", datetime.now().strftime("%a")))
        self.month_label.setText(_translate("Homescreen", datetime.now().strftime("%B")))
        self.day_label.setText(_translate("Homescreen", datetime.now().strftime("%d")))
        self.date_separator_label.setText(_translate("Homescreen", ","))
        self.year_label.setText(_translate("Homescreen", datetime.now().strftime("%Y")))
        self.time_separator.setText(_translate("Homescreen", ":"))
        self.am_pm_label.setText(_translate("Homescreen", datetime.now().strftime("%p")))
        self.homescreen_temperature_label.setText(_translate("Homescreen", " 23 ºC"))
        self.settings_button.setText(_translate("Homescreen", "⚙️"))
        self.ambient_button.setText(_translate("Homescreen", "Ambient"))
        self.security_button.setText(_translate("Homescreen", "Security"))
        self.lock_button.setText(_translate("Homescreen", "🔒"))

    def setupUiAm(self, Form, setupUiHS):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(749, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(749, 391))
        Form.setMaximumSize(QtCore.QSize(749, 391))
        Form.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(True)
        Form.setTabletTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(True)
        Form.setAutoFillBackground(True)
        self.Ambient_Frame = QtWidgets.QFrame(Form)
        self.Ambient_Frame.setGeometry(QtCore.QRect(0, 0, 749, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ambient_Frame.sizePolicy().hasHeightForWidth())
        self.Ambient_Frame.setSizePolicy(sizePolicy)
        self.Ambient_Frame.setAutoFillBackground(False)
        self.Ambient_Frame.setStyleSheet("background-color: rgb(16, 128, 128);")
        self.Ambient_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Ambient_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Ambient_Frame.setLineWidth(0)
        self.Ambient_Frame.setObjectName("Ambient_Frame")
        self.minutes_label = QtWidgets.QLCDNumber(self.Ambient_Frame)
        self.minutes_label.setGeometry(QtCore.QRect(660, 10, 41, 41))
        self.minutes_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.minutes_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minutes_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minutes_label.setDigitCount(2)
        self.minutes_label.setProperty("intValue", 88)
        self.minutes_label.setObjectName("minutes_label")
        self.hour_label = QtWidgets.QLCDNumber(self.Ambient_Frame)
        self.hour_label.setGeometry(QtCore.QRect(610, 10, 41, 41))
        self.hour_label.setAutoFillBackground(False)
        self.hour_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.hour_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hour_label.setDigitCount(2)
        self.hour_label.setProperty("intValue", 88)
        self.hour_label.setObjectName("hour_label")
        self.ambient_screen_title_label = QtWidgets.QLabel(self.Ambient_Frame)
        self.ambient_screen_title_label.setGeometry(QtCore.QRect(250, 90, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.ambient_screen_title_label.setFont(font)
        self.ambient_screen_title_label.setObjectName("ambient_screen_title_label")
        self.time_separator_label = QtWidgets.QLabel(self.Ambient_Frame)
        self.time_separator_label.setGeometry(QtCore.QRect(650, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_separator_label.setFont(font)
        self.time_separator_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.time_separator_label.setObjectName("time_separator_label")
        self.am_pm_label = QtWidgets.QLabel(self.Ambient_Frame)
        self.am_pm_label.setGeometry(QtCore.QRect(700, 30, 31, 21))
        self.am_pm_label.setObjectName("am_pm_label")
        self.date_label = QtWidgets.QLabel(self.Ambient_Frame)
        self.date_label.setGeometry(QtCore.QRect(630, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.date_label.setInputMethodHints(QtCore.Qt.ImhDate)
        self.date_label.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.date_label.setObjectName("date_label")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Ambient_Frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 230, 191, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lighting_widget_title = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lighting_widget_title.setFont(font)
        self.lighting_widget_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lighting_widget_title.setObjectName("lighting_widget_title")
        self.verticalLayout_4.addWidget(self.lighting_widget_title)
        self.lighting_percentage_label_ = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lighting_percentage_label_.setFont(font)
        self.lighting_percentage_label_.setAlignment(QtCore.Qt.AlignCenter)
        self.lighting_percentage_label_.setObjectName("lighting_percentage_label_")
        self.verticalLayout_4.addWidget(self.lighting_percentage_label_)
        self.lighting_slider = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.lighting_slider.setProperty("value", 84)
        self.lighting_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lighting_slider.setObjectName("lighting_slider")
        self.verticalLayout_4.addWidget(self.lighting_slider)
        self.light_color_selector = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.light_color_selector.setFont(font)
        self.light_color_selector.setObjectName("light_color_selector")
        self.light_color_selector.addItem("")
        self.light_color_selector.addItem("")
        self.light_color_selector.addItem("")
        self.light_color_selector.addItem("")
        self.light_color_selector.addItem("")
        self.light_color_selector.addItem("")
        self.light_color_selector.addItem("")
        self.light_color_selector.addItem("")
        self.light_color_selector.addItem("")
        self.verticalLayout_4.addWidget(self.light_color_selector)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Ambient_Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 230, 235, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.audio_widget_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.audio_widget_title.setFont(font)
        self.audio_widget_title.setAlignment(QtCore.Qt.AlignCenter)
        self.audio_widget_title.setObjectName("audio_widget_title")
        self.verticalLayout_2.addWidget(self.audio_widget_title, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.skip_back_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.skip_back_button.setObjectName("skip_back_button")
        self.horizontalLayout.addWidget(self.skip_back_button)
        self.play_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.play_button.setObjectName("play_button")
        self.horizontalLayout.addWidget(self.play_button)
        self.skip_fwd_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.skip_fwd_button.setObjectName("skip_fwd_button")
        self.horizontalLayout.addWidget(self.skip_fwd_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.volume_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.volume_slider.setProperty("value", 40)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.verticalLayout_2.addWidget(self.volume_slider)
        self.temp_units_selector_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.temp_units_selector_2.setFont(font)
        self.temp_units_selector_2.setObjectName("temp_units_selector_2")
        self.temp_units_selector_2.addItem("")
        self.temp_units_selector_2.addItem("")
        self.temp_units_selector_2.addItem("")
        self.temp_units_selector_2.setItemText(2, "")
        self.verticalLayout_2.addWidget(self.temp_units_selector_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Ambient_Frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 230, 195, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.temperature_widget_title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.temperature_widget_title.setFont(font)
        self.temperature_widget_title.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature_widget_title.setObjectName("temperature_widget_title")
        self.verticalLayout_3.addWidget(self.temperature_widget_title)
        self.temperature_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.temperature_label.setFont(font)
        self.temperature_label.setObjectName("temperature_label")
        self.verticalLayout_3.addWidget(self.temperature_label, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.temperature_slider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.temperature_slider.setFont(font)
        self.temperature_slider.setMinimum(0)
        self.temperature_slider.setProperty("value", 70)
        self.temperature_slider.setOrientation(QtCore.Qt.Horizontal)
        self.temperature_slider.setObjectName("temperature_slider")
        self.verticalLayout_3.addWidget(self.temperature_slider)
        self.temp_units_selector = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.temp_units_selector.setFont(font)
        self.temp_units_selector.setObjectName("temp_units_selector")
        self.temp_units_selector.addItem("")
        self.temp_units_selector.addItem("")
        self.verticalLayout_3.addWidget(self.temp_units_selector)
        self.ambient_room_selector = QtWidgets.QComboBox(self.Ambient_Frame)
        self.ambient_room_selector.setGeometry(QtCore.QRect(290, 0, 165, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ambient_room_selector.setFont(font)
        self.ambient_room_selector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ambient_room_selector.setAcceptDrops(True)
        self.ambient_room_selector.setFrame(True)
        self.ambient_room_selector.setObjectName("ambient_room_selector")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.ambient_room_selector.addItem("")
        self.back_button = QtWidgets.QPushButton(self.Ambient_Frame)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")
        self.lock_button = QtWidgets.QPushButton(self.Ambient_Frame)
        self.lock_button.setGeometry(QtCore.QRect(150, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lock_button.setFont(font)
        self.lock_button.setObjectName("lock_button")
        self.minutes_label.raise_()
        self.hour_label.raise_()
        self.ambient_screen_title_label.raise_()
        self.time_separator_label.raise_()
        self.date_label.raise_()
        self.am_pm_label.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.ambient_room_selector.raise_()
        self.back_button.raise_()
        self.lock_button.raise_()

        self.retranslateUiAm(Form, setupUiHS)

        # button leading back to HomeScreen
        self.back_button.pressed.connect(setupUiHS.show)
        self.back_button.pressed.connect(Form.close)
        self.lock_button.pressed.connect(Form.close)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUiAm(self, Form, setupUiHS):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ambient"))
        self.ambient_screen_title_label.setText(_translate("Form", "Ambient"))
        self.time_separator_label.setText(_translate("Form", ":"))
        self.am_pm_label.setText(_translate("Form", "AM"))
        self.date_label.setText(_translate("Form", "mm/dd/year"))
        self.lighting_widget_title.setText(_translate("Form", "Lighting"))
        self.lighting_percentage_label_.setText(_translate("Form", "0%"))
        self.light_color_selector.setItemText(0, _translate("Form", "White"))
        self.light_color_selector.setItemText(1, _translate("Form", "Yellow"))
        self.light_color_selector.setItemText(2, _translate("Form", "Green"))
        self.light_color_selector.setItemText(3, _translate("Form", "Blue"))
        self.light_color_selector.setItemText(4, _translate("Form", "Light Blue"))
        self.light_color_selector.setItemText(5, _translate("Form", "Red"))
        self.light_color_selector.setItemText(6, _translate("Form", "Pink"))
        self.light_color_selector.setItemText(7, _translate("Form", "Purple"))
        self.light_color_selector.setItemText(8, _translate("Form", "Magenta"))
        self.audio_widget_title.setText(_translate("Form", "Audio"))
        self.skip_back_button.setText(_translate("Form", "<<"))
        self.play_button.setText(_translate("Form", "►||"))
        self.skip_fwd_button.setText(_translate("Form", ">>"))
        self.temp_units_selector_2.setItemText(0, _translate("Form", "General Intercom"))
        self.temp_units_selector_2.setItemText(1, _translate("Form", "Room"))
        self.temperature_widget_title.setText(_translate("Form", "Temperature"))
        self.temperature_label.setText(_translate("Form", "0ºC"))
        self.temp_units_selector.setItemText(0, _translate("Form", "Fahrenheit"))
        self.temp_units_selector.setItemText(1, _translate("Form", "Celcius"))
        self.ambient_room_selector.setCurrentText(_translate("Form", "Whole House"))
        self.ambient_room_selector.setItemText(0, _translate("Form", "Whole House"))
        self.ambient_room_selector.setItemText(1, _translate("Form", "Master"))
        self.ambient_room_selector.setItemText(2, _translate("Form", "Bedroom1"))
        self.ambient_room_selector.setItemText(3, _translate("Form", "Bedroom2"))
        self.ambient_room_selector.setItemText(4, _translate("Form", "Living"))
        self.ambient_room_selector.setItemText(5, _translate("Form", "Family"))
        self.ambient_room_selector.setItemText(6, _translate("Form", "Guest"))
        self.ambient_room_selector.setItemText(7, _translate("Form", "Kitchen"))
        self.ambient_room_selector.setItemText(8, _translate("Form", "Dining"))
        self.ambient_room_selector.setItemText(9, _translate("Form", "Game"))
        self.ambient_room_selector.setItemText(10, _translate("Form", "Bathroom 1"))
        self.ambient_room_selector.setItemText(11, _translate("Form", "Bathroom 2"))
        self.ambient_room_selector.setItemText(12, _translate("Form", "Basement"))
        self.ambient_room_selector.setItemText(13, _translate("Form", "Library"))
        self.ambient_room_selector.setItemText(14, _translate("Form", "Gym"))
        self.ambient_room_selector.setItemText(15, _translate("Form", "Storage"))
        self.ambient_room_selector.setItemText(16, _translate("Form", "Garage"))
        self.back_button.setText(_translate("Form", "🔙"))
        self.lock_button.setText(_translate("Form", "🔒"))

    def setupUiSec(self, Form, setupUiHS):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(749, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(749, 391))
        Form.setMaximumSize(QtCore.QSize(749, 391))
        Form.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(True)
        Form.setTabletTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(True)
        Form.setAutoFillBackground(True)

        self.Security_Frame = QtWidgets.QFrame(Form)
        self.Security_Frame.setGeometry(QtCore.QRect(0, 0, 749, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Security_Frame.sizePolicy().hasHeightForWidth())
        self.Security_Frame.setSizePolicy(sizePolicy)
        self.Security_Frame.setAutoFillBackground(False)
        self.Security_Frame.setStyleSheet("background-color: rgb(16, 128, 128);")
        self.Security_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Security_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Security_Frame.setLineWidth(0)
        self.Security_Frame.setObjectName("Security_Frame")

        # back to the Home Screen
        self.back_button = QtWidgets.QPushButton(self.Security_Frame)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")

        # displays the hour
        self.hour_label = QtWidgets.QLCDNumber(self.Security_Frame)
        self.hour_label.setGeometry(QtCore.QRect(610, 10, 41, 41))
        self.hour_label.setAutoFillBackground(False)
        self.hour_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.hour_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hour_label.setDigitCount(2)
        self.hour_label.setProperty("intValue", 88)
        self.hour_label.setObjectName("hour_label")

        # displays the minutes
        self.minutes_label = QtWidgets.QLCDNumber(self.Security_Frame)
        self.minutes_label.setGeometry(QtCore.QRect(660, 10, 41, 41))
        self.minutes_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.minutes_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minutes_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minutes_label.setDigitCount(2)
        self.minutes_label.setProperty("intValue", 88)
        self.minutes_label.setObjectName("minutes_label")

        self.security_title_label = QtWidgets.QLabel(self.Security_Frame)
        self.security_title_label.setGeometry(QtCore.QRect(250, 50, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.security_title_label.setFont(font)
        self.security_title_label.setObjectName("security_title_label")

        # two dots in between hour and minutes
        self.time_separator_label = QtWidgets.QLabel(self.Security_Frame)
        self.time_separator_label.setGeometry(QtCore.QRect(650, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_separator_label.setFont(font)
        self.time_separator_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.time_separator_label.setObjectName("time_separator_label")

        # displays AM or PM
        self.am_pm_label = QtWidgets.QLabel(self.Security_Frame)
        self.am_pm_label.setGeometry(QtCore.QRect(700, 30, 31, 21))
        self.am_pm_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.am_pm_label.setObjectName("am_pm_label")

        # contains everything related to the date
        self.date_label = QtWidgets.QLabel(self.Security_Frame)
        self.date_label.setGeometry(QtCore.QRect(630, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.date_label.setInputMethodHints(QtCore.Qt.ImhDate)
        self.date_label.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.date_label.setObjectName("date_label")

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Security_Frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 240, 171, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.video_feed_widget_lable = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.video_feed_widget_lable.setFont(font)
        self.video_feed_widget_lable.setObjectName("video_feed_widget_lable")
        self.verticalLayout_3.addWidget(self.video_feed_widget_lable, 0, QtCore.Qt.AlignHCenter)
        self.play_video_label = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.play_video_label.setObjectName("play_video_label")
        self.verticalLayout_3.addWidget(self.play_video_label)

        # comboBox that has the rooms of the entire house
        self.video_room_selector = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.video_room_selector.setFont(font)
        self.video_room_selector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.video_room_selector.setAcceptDrops(True)
        self.video_room_selector.setFrame(True)
        self.video_room_selector.setObjectName("video_room_selector")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.verticalLayout_3.addWidget(self.video_room_selector)

        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Security_Frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(120, 130, 491, 107))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.arm_away_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.arm_away_button.setObjectName("arm_away_button")
        self.horizontalLayout_3.addWidget(self.arm_away_button)

        self.arm_stay_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.arm_stay_button.setObjectName("arm_stay_button")
        self.horizontalLayout_3.addWidget(self.arm_stay_button)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Security_Frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(440, 240, 173, 83))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.entry_control_widget_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.entry_control_widget_label.setFont(font)
        self.entry_control_widget_label.setObjectName("entry_control_widget_label")
        self.verticalLayout_4.addWidget(self.entry_control_widget_label, 0, QtCore.Qt.AlignHCenter)

        self.door_lock_button_box = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_3)
        self.door_lock_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close | QtWidgets.QDialogButtonBox.Open)
        self.door_lock_button_box.setCenterButtons(True)
        self.door_lock_button_box.setObjectName("door_lock_button_box")
        self.verticalLayout_4.addWidget(self.door_lock_button_box)

        self.entry_selector = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.entry_selector.setFont(font)
        self.entry_selector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.entry_selector.setAcceptDrops(True)
        self.entry_selector.setFrame(True)
        self.entry_selector.setObjectName("entry_selector")
        self.entry_selector.addItem("")
        self.entry_selector.addItem("")
        self.entry_selector.addItem("")
        self.entry_selector.addItem("")
        self.entry_selector.addItem("")
        self.verticalLayout_4.addWidget(self.entry_selector)

        self.lock_button = QtWidgets.QPushButton(self.Security_Frame)
        self.lock_button.setGeometry(QtCore.QRect(150, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lock_button.setFont(font)
        self.lock_button.setObjectName("lock_button")

        self.back_button.raise_()
        self.minutes_label.raise_()
        self.hour_label.raise_()
        self.time_separator_label.raise_()
        self.date_label.raise_()
        self.am_pm_label.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.security_title_label.raise_()
        self.lock_button.raise_()

        self.retranslateUiSec(Form, setupUiHS)

        # button leading back to HomeScreen
        self.back_button.pressed.connect(setupUiHS.show)
        self.back_button.pressed.connect(Form.close)
        self.lock_button.pressed.connect(Form.close)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUiSec(self, Form, setupUiHS):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Security"))
        self.back_button.setText(_translate("Form", "🔙"))
        self.security_title_label.setText(_translate("Form", "Security"))
        self.time_separator_label.setText(_translate("Form", ":"))
        self.am_pm_label.setText(_translate("Form", "AM"))
        self.date_label.setText(_translate("Form", "mm/dd/year"))
        self.video_feed_widget_lable.setText(_translate("Form", "Video Feed"))
        self.play_video_label.setText(_translate("Form", "Play Feed"))
        self.video_room_selector.setCurrentText(_translate("Form", "Master"))
        self.video_room_selector.setItemText(0, _translate("Form", "Master"))
        self.video_room_selector.setItemText(1, _translate("Form", "Bedroom1"))
        self.video_room_selector.setItemText(2, _translate("Form", "Bedroom2"))
        self.video_room_selector.setItemText(3, _translate("Form", "Living"))
        self.video_room_selector.setItemText(4, _translate("Form", "Family"))
        self.video_room_selector.setItemText(5, _translate("Form", "Guest"))
        self.video_room_selector.setItemText(6, _translate("Form", "Kitchen"))
        self.video_room_selector.setItemText(7, _translate("Form", "Dining"))
        self.video_room_selector.setItemText(8, _translate("Form", "Game"))
        self.video_room_selector.setItemText(9, _translate("Form", "Bathroom 1"))
        self.video_room_selector.setItemText(10, _translate("Form", "Bathroom 2"))
        self.video_room_selector.setItemText(11, _translate("Form", "Basement"))
        self.video_room_selector.setItemText(12, _translate("Form", "Library"))
        self.video_room_selector.setItemText(13, _translate("Form", "Gym"))
        self.video_room_selector.setItemText(14, _translate("Form", "Storage"))
        self.video_room_selector.setItemText(15, _translate("Form", "Garage"))
        self.arm_away_button.setText(_translate("Form", "Arm/Away"))
        self.arm_stay_button.setText(_translate("Form", "Arm/Stay"))
        self.entry_control_widget_label.setText(_translate("Form", "Entry Control"))
        self.entry_selector.setCurrentText(_translate("Form", "Whole House"))
        self.entry_selector.setItemText(0, _translate("Form", "Whole House"))
        self.entry_selector.setItemText(1, _translate("Form", "Main Entrance Door"))
        self.entry_selector.setItemText(2, _translate("Form", "Kitchen Door"))
        self.entry_selector.setItemText(3, _translate("Form", "Master Bedroom Door"))
        self.entry_selector.setItemText(4, _translate("Form", "Garage Door"))
        self.lock_button.setText(_translate("Form", "🔒"))

    def setupUiSet(self, Form, setupUiHS):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(749, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(749, 391))
        Form.setMaximumSize(QtCore.QSize(749, 391))
        Form.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(True)
        Form.setTabletTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(True)
        Form.setAutoFillBackground(True)
        self.Settings_Frame = QtWidgets.QFrame(Form)
        self.Settings_Frame.setGeometry(QtCore.QRect(0, 0, 749, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Settings_Frame.sizePolicy().hasHeightForWidth())
        self.Settings_Frame.setSizePolicy(sizePolicy)
        self.Settings_Frame.setAutoFillBackground(False)
        self.Settings_Frame.setStyleSheet("background-color: rgb(16, 128, 128);")
        self.Settings_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Settings_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Settings_Frame.setLineWidth(0)
        self.Settings_Frame.setObjectName("Settings_Frame")
        self.minutes_label = QtWidgets.QLCDNumber(self.Settings_Frame)
        self.minutes_label.setGeometry(QtCore.QRect(660, 10, 41, 41))
        self.minutes_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n")
        self.minutes_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.minutes_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minutes_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minutes_label.setDigitCount(2)
        self.minutes_label.setProperty("intValue", 88)
        self.minutes_label.setObjectName("minutes_label")
        self.hour_label = QtWidgets.QLCDNumber(self.Settings_Frame)
        self.hour_label.setGeometry(QtCore.QRect(610, 10, 41, 41))
        self.hour_label.setAutoFillBackground(False)
        self.hour_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hour_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.hour_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hour_label.setDigitCount(2)
        self.hour_label.setProperty("intValue", 88)
        self.hour_label.setObjectName("hour_label")
        self.ambient_screen_title_label = QtWidgets.QLabel(self.Settings_Frame)
        self.ambient_screen_title_label.setGeometry(QtCore.QRect(250, 20, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.ambient_screen_title_label.setFont(font)
        self.ambient_screen_title_label.setAutoFillBackground(False)
        self.ambient_screen_title_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.ambient_screen_title_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ambient_screen_title_label.setLineWidth(0)
        self.ambient_screen_title_label.setScaledContents(False)
        self.ambient_screen_title_label.setObjectName("ambient_screen_title_label")
        self.time_separator_label = QtWidgets.QLabel(self.Settings_Frame)
        self.time_separator_label.setGeometry(QtCore.QRect(650, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_separator_label.setFont(font)
        self.time_separator_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.time_separator_label.setObjectName("time_separator_label")
        self.am_pm_label = QtWidgets.QLabel(self.Settings_Frame)
        self.am_pm_label.setGeometry(QtCore.QRect(700, 30, 31, 21))
        self.am_pm_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.am_pm_label.setObjectName("am_pm_label")
        self.date_label = QtWidgets.QLabel(self.Settings_Frame)
        self.date_label.setGeometry(QtCore.QRect(630, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.date_label.setInputMethodHints(QtCore.Qt.ImhDate)
        self.date_label.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.date_label.setObjectName("date_label")
        self.back_button = QtWidgets.QPushButton(self.Settings_Frame)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet("")
        self.back_button.setAutoDefault(False)
        self.back_button.setDefault(True)
        self.back_button.setObjectName("back_button")
        self.label = QtWidgets.QLabel(self.Settings_Frame)
        self.label.setGeometry(QtCore.QRect(560, 370, 191, 21))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")
        self.open_log_commandLinkButton = QtWidgets.QCommandLinkButton(self.Settings_Frame)
        self.open_log_commandLinkButton.setGeometry(QtCore.QRect(110, 210, 521, 46))
        self.open_log_commandLinkButton.setAutoFillBackground(False)
        self.open_log_commandLinkButton.setStyleSheet("background-color: rgba(255, 255, 255, 124);")
        self.open_log_commandLinkButton.setDefault(True)
        self.open_log_commandLinkButton.setObjectName("open_log_commandLinkButton")
        self.layoutWidget = QtWidgets.QWidget(self.Settings_Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 130, 519, 79))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.set_password_label = QtWidgets.QLabel(self.layoutWidget)
        self.set_password_label.setEnabled(True)
        self.set_password_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.set_password_label.setLineWidth(0)
        self.set_password_label.setObjectName("set_password_label")
        self.horizontalLayout.addWidget(self.set_password_label)
        self.password_spinBox_1 = QtWidgets.QSpinBox(self.layoutWidget)
        self.password_spinBox_1.setAutoFillBackground(False)
        self.password_spinBox_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.password_spinBox_1.setObjectName("password_spinBox_1")
        self.horizontalLayout.addWidget(self.password_spinBox_1)
        self.password_spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.password_spinBox_2.setAutoFillBackground(False)
        self.password_spinBox_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.password_spinBox_2.setObjectName("password_spinBox_2")
        self.horizontalLayout.addWidget(self.password_spinBox_2)
        self.password_spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.password_spinBox_3.setAutoFillBackground(False)
        self.password_spinBox_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.password_spinBox_3.setObjectName("password_spinBox_3")
        self.horizontalLayout.addWidget(self.password_spinBox_3)
        self.password_spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget)
        self.password_spinBox_4.setAutoFillBackground(False)
        self.password_spinBox_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.password_spinBox_4.setObjectName("password_spinBox_4")
        self.horizontalLayout.addWidget(self.password_spinBox_4)

        self.lock_button = QtWidgets.QPushButton(self.Settings_Frame)
        self.lock_button.setGeometry(QtCore.QRect(150, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lock_button.setFont(font)
        self.lock_button.setObjectName("lock_button")

        self.minutes_label.raise_()
        self.hour_label.raise_()
        self.ambient_screen_title_label.raise_()
        self.time_separator_label.raise_()
        self.date_label.raise_()
        self.am_pm_label.raise_()
        self.back_button.raise_()
        self.label.raise_()
        self.open_log_commandLinkButton.raise_()
        self.layoutWidget.raise_()
        self.lock_button.raise_()

        self.retranslateUiSet(Form, setupUiHS)

        # button leading back to HomeScreen
        self.back_button.pressed.connect(setupUiHS.show)
        self.back_button.pressed.connect(Form.close)
        self.lock_button.pressed.connect(Form.close)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUiSet(self, Form, setupUiHS):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.ambient_screen_title_label.setText(_translate("Form", "Settings"))
        self.time_separator_label.setText(_translate("Form", ":"))
        self.am_pm_label.setText(_translate("Form", "AM"))
        self.date_label.setText(_translate("Form", "mm/dd/year"))
        self.back_button.setText(_translate("Form", "🔙"))
        self.label.setText(_translate("Form", "AutoHome Application(1.0.0)"))
        self.open_log_commandLinkButton.setText(_translate("Form", "Open Home Activity Log"))
        self.set_password_label.setText(_translate("Form", "Set Password:"))
        self.lock_button.setText(_translate("Form", "🔒"))
