# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeScreen.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Homescreen(object):
    def setupUi(self, Homescreen):
        Homescreen.setObjectName("Homescreen")
        Homescreen.setWindowModality(QtCore.Qt.NonModal)
        Homescreen.resize(749, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Homescreen.sizePolicy().hasHeightForWidth())
        Homescreen.setSizePolicy(sizePolicy)
        Homescreen.setSizeIncrement(QtCore.QSize(1, 1))
        Homescreen.setAcceptDrops(True)
        Homescreen.setAutoFillBackground(True)
        Homescreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Homescreen)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_Frame.setGeometry(QtCore.QRect(0, 0, 749, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_Frame.sizePolicy().hasHeightForWidth())
        self.Main_Frame.setSizePolicy(sizePolicy)
        self.Main_Frame.setAutoFillBackground(False)
        self.Main_Frame.setStyleSheet("background-color: rgb(16, 128, 128);")
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Main_Frame.setLineWidth(0)
        self.Main_Frame.setObjectName("Main_Frame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Main_Frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(250, 180, 241, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.weekday_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.weekday_label.setFont(font)
        self.weekday_label.setObjectName("weekday_label")
        self.horizontalLayout_2.addWidget(self.weekday_label)
        self.month_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.month_label.setFont(font)
        self.month_label.setObjectName("month_label")
        self.horizontalLayout_2.addWidget(self.month_label)
        self.day_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.day_label.setFont(font)
        self.day_label.setObjectName("day_label")
        self.horizontalLayout_2.addWidget(self.day_label)
        self.date_separator_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.date_separator_label.setFont(font)
        self.date_separator_label.setObjectName("date_separator_label")
        self.horizontalLayout_2.addWidget(self.date_separator_label)
        self.year_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.year_label.setFont(font)
        self.year_label.setObjectName("year_label")
        self.horizontalLayout_2.addWidget(self.year_label)
        self.time_separator = QtWidgets.QLabel(self.Main_Frame)
        self.time_separator.setGeometry(QtCore.QRect(310, 60, 117, 119))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.time_separator.setFont(font)
        self.time_separator.setTextFormat(QtCore.Qt.AutoText)
        self.time_separator.setScaledContents(True)
        self.time_separator.setAlignment(QtCore.Qt.AlignCenter)
        self.time_separator.setWordWrap(True)
        self.time_separator.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.time_separator.setObjectName("time_separator")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Main_Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 60, 281, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hour_label = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.hour_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.hour_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hour_label.setDigitCount(2)
        self.hour_label.setProperty("intValue", 88)
        self.hour_label.setObjectName("hour_label")
        self.horizontalLayout.addWidget(self.hour_label)
        self.minutes_label = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.minutes_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.minutes_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minutes_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minutes_label.setDigitCount(2)
        self.minutes_label.setProperty("intValue", 88)
        self.minutes_label.setObjectName("minutes_label")
        self.horizontalLayout.addWidget(self.minutes_label)
        self.am_pm_label = QtWidgets.QLabel(self.Main_Frame)
        self.am_pm_label.setGeometry(QtCore.QRect(510, 150, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.am_pm_label.setFont(font)
        self.am_pm_label.setObjectName("am_pm_label")
        self.homescreen_temperature_label = QtWidgets.QLabel(self.Main_Frame)
        self.homescreen_temperature_label.setGeometry(QtCore.QRect(680, 0, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.homescreen_temperature_label.setFont(font)
        self.homescreen_temperature_label.setObjectName("homescreen_temperature_label")
        self.lock_button = QtWidgets.QPushButton(self.Main_Frame)
        self.lock_button.setGeometry(QtCore.QRect(0, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.lock_button.setFont(font)
        self.lock_button.setObjectName("lock_button")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Main_Frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(130, 240, 491, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ambient_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ambient_button.setObjectName("ambient_button")
        self.horizontalLayout_4.addWidget(self.ambient_button)
        self.security_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.security_button.setObjectName("security_button")
        self.horizontalLayout_4.addWidget(self.security_button)
        Homescreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(Homescreen)
        QtCore.QMetaObject.connectSlotsByName(Homescreen)

    def retranslateUi(self, Homescreen):
        _translate = QtCore.QCoreApplication.translate
        Homescreen.setWindowTitle(_translate("Homescreen", "MainWindow"))
        self.weekday_label.setText(_translate("Homescreen", "Weekday"))
        self.month_label.setText(_translate("Homescreen", "Month"))
        self.day_label.setText(_translate("Homescreen", "Day"))
        self.date_separator_label.setText(_translate("Homescreen", ","))
        self.year_label.setText(_translate("Homescreen", "Year"))
        self.time_separator.setText(_translate("Homescreen", ":"))
        self.am_pm_label.setText(_translate("Homescreen", "AM"))
        self.homescreen_temperature_label.setText(_translate("Homescreen", " 23 ºC"))
        self.lock_button.setText(_translate("Homescreen", "🔒"))
        self.ambient_button.setText(_translate("Homescreen", "Ambient"))
        self.security_button.setText(_translate("Homescreen", "Security"))
