# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LockScreen.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(749, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(749, 391))
        Form.setMaximumSize(QtCore.QSize(749, 391))
        Form.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(False)
        Form.setTabletTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(True)
        Form.setAutoFillBackground(False)
        self.Lockscreen_Frame = QtWidgets.QFrame(Form)
        self.Lockscreen_Frame.setGeometry(QtCore.QRect(0, 0, 749, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lockscreen_Frame.sizePolicy().hasHeightForWidth())
        self.Lockscreen_Frame.setSizePolicy(sizePolicy)
        self.Lockscreen_Frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Lockscreen_Frame.setMouseTracking(True)
        self.Lockscreen_Frame.setAutoFillBackground(False)
        self.Lockscreen_Frame.setStyleSheet("background-color: rgb(16, 128, 128);")
        self.Lockscreen_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Lockscreen_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Lockscreen_Frame.setLineWidth(0)
        self.Lockscreen_Frame.setObjectName("Lockscreen_Frame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Lockscreen_Frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(250, 180, 241, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.weekday_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.weekday_label.setFont(font)
        self.weekday_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.weekday_label.setObjectName("weekday_label")
        self.horizontalLayout_2.addWidget(self.weekday_label)
        self.month_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.month_label.setFont(font)
        self.month_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.month_label.setObjectName("month_label")
        self.horizontalLayout_2.addWidget(self.month_label)
        self.day_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.day_label.setFont(font)
        self.day_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.day_label.setObjectName("day_label")
        self.horizontalLayout_2.addWidget(self.day_label)
        self.date_separator_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.date_separator_label.setFont(font)
        self.date_separator_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.date_separator_label.setObjectName("date_separator_label")
        self.horizontalLayout_2.addWidget(self.date_separator_label)
        self.year_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.year_label.setFont(font)
        self.year_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.year_label.setObjectName("year_label")
        self.horizontalLayout_2.addWidget(self.year_label)
        self.time_separator = QtWidgets.QLabel(self.Lockscreen_Frame)
        self.time_separator.setGeometry(QtCore.QRect(310, 60, 117, 119))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.time_separator.setFont(font)
        self.time_separator.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.time_separator.setTextFormat(QtCore.Qt.AutoText)
        self.time_separator.setScaledContents(True)
        self.time_separator.setAlignment(QtCore.Qt.AlignCenter)
        self.time_separator.setWordWrap(True)
        self.time_separator.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.time_separator.setObjectName("time_separator")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Lockscreen_Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 60, 281, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hour_label = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.hour_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hour_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.hour_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hour_label.setDigitCount(2)
        self.hour_label.setProperty("intValue", 88)
        self.hour_label.setObjectName("hour_label")
        self.horizontalLayout.addWidget(self.hour_label)
        self.minutes_label = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.minutes_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.minutes_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.minutes_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minutes_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minutes_label.setDigitCount(2)
        self.minutes_label.setProperty("intValue", 88)
        self.minutes_label.setObjectName("minutes_label")
        self.horizontalLayout.addWidget(self.minutes_label)
        self.am_pm_label = QtWidgets.QLabel(self.Lockscreen_Frame)
        self.am_pm_label.setGeometry(QtCore.QRect(510, 150, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.am_pm_label.setFont(font)
        self.am_pm_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.am_pm_label.setObjectName("am_pm_label")
        self.homescreen_temperature_label = QtWidgets.QLabel(self.Lockscreen_Frame)
        self.homescreen_temperature_label.setGeometry(QtCore.QRect(680, 0, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.homescreen_temperature_label.setFont(font)
        self.homescreen_temperature_label.setObjectName("homescreen_temperature_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Lockscreen_Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(248, 220, 241, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.keypad_button_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_5.setObjectName("keypad_button_5")
        self.gridLayout.addWidget(self.keypad_button_5, 2, 1, 1, 1)
        self.pswrd_processbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.pswrd_processbar.setMaximum(4)
        self.pswrd_processbar.setProperty("value", 0)
        self.pswrd_processbar.setObjectName("pswrd_processbar")
        self.gridLayout.addWidget(self.pswrd_processbar, 0, 0, 1, 3)
        self.keypad_button_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_2.setObjectName("keypad_button_2")
        self.gridLayout.addWidget(self.keypad_button_2, 1, 1, 1, 1)
        self.keypad_button_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_3.setObjectName("keypad_button_3")
        self.gridLayout.addWidget(self.keypad_button_3, 1, 2, 1, 1)
        self.keypad_button_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_8.setObjectName("keypad_button_8")
        self.gridLayout.addWidget(self.keypad_button_8, 3, 1, 1, 1)
        self.keypad_button_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_1.setObjectName("keypad_button_1")
        self.gridLayout.addWidget(self.keypad_button_1, 1, 0, 1, 1)
        self.keypad_button_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_6.setObjectName("keypad_button_6")
        self.gridLayout.addWidget(self.keypad_button_6, 2, 2, 1, 1)
        self.keypad_button_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_7.setObjectName("keypad_button_7")
        self.gridLayout.addWidget(self.keypad_button_7, 3, 0, 1, 1)
        self.keypad_button_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_4.setObjectName("keypad_button_4")
        self.gridLayout.addWidget(self.keypad_button_4, 2, 0, 1, 1)
        self.keypad_button_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_9.setAutoFillBackground(False)
        self.keypad_button_9.setObjectName("keypad_button_9")
        self.gridLayout.addWidget(self.keypad_button_9, 3, 2, 1, 1)
        self.keypad_button_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.keypad_button_0.setObjectName("keypad_button_0")
        self.gridLayout.addWidget(self.keypad_button_0, 4, 1, 1, 1)
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.am_pm_label.raise_()
        self.homescreen_temperature_label.raise_()
        self.gridLayoutWidget.raise_()
        self.time_separator.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.weekday_label.setText(_translate("Form", "Weekday"))
        self.month_label.setText(_translate("Form", "Month"))
        self.day_label.setText(_translate("Form", "Day"))
        self.date_separator_label.setText(_translate("Form", ","))
        self.year_label.setText(_translate("Form", "Year"))
        self.time_separator.setText(_translate("Form", ":"))
        self.am_pm_label.setText(_translate("Form", "AM"))
        self.homescreen_temperature_label.setText(_translate("Form", " 23 ºC"))
        self.keypad_button_5.setText(_translate("Form", "5"))
        self.keypad_button_2.setText(_translate("Form", "2"))
        self.keypad_button_3.setText(_translate("Form", "3"))
        self.keypad_button_8.setText(_translate("Form", "8"))
        self.keypad_button_1.setText(_translate("Form", "1"))
        self.keypad_button_6.setText(_translate("Form", "6"))
        self.keypad_button_7.setText(_translate("Form", "7"))
        self.keypad_button_4.setText(_translate("Form", "4"))
        self.keypad_button_9.setText(_translate("Form", "9"))
        self.keypad_button_0.setText(_translate("Form", "0"))
