# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Security.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(749, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(749, 391))
        Form.setMaximumSize(QtCore.QSize(749, 391))
        Form.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(True)
        Form.setTabletTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(True)
        Form.setAutoFillBackground(True)
        self.Security_Frame = QtWidgets.QFrame(Form)
        self.Security_Frame.setGeometry(QtCore.QRect(0, 0, 749, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Security_Frame.sizePolicy().hasHeightForWidth())
        self.Security_Frame.setSizePolicy(sizePolicy)
        self.Security_Frame.setAutoFillBackground(True)
        self.Security_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Security_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Security_Frame.setLineWidth(0)
        self.Security_Frame.setObjectName("Security_Frame")
        self.back_button = QtWidgets.QPushButton(self.Security_Frame)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")
        self.minutes_label = QtWidgets.QLCDNumber(self.Security_Frame)
        self.minutes_label.setGeometry(QtCore.QRect(660, 10, 41, 41))
        self.minutes_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.minutes_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minutes_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minutes_label.setDigitCount(2)
        self.minutes_label.setProperty("intValue", 88)
        self.minutes_label.setObjectName("minutes_label")
        self.hour_label = QtWidgets.QLCDNumber(self.Security_Frame)
        self.hour_label.setGeometry(QtCore.QRect(610, 10, 41, 41))
        self.hour_label.setAutoFillBackground(False)
        self.hour_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.hour_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hour_label.setDigitCount(2)
        self.hour_label.setProperty("intValue", 88)
        self.hour_label.setObjectName("hour_label")
        self.security_title_label = QtWidgets.QLabel(self.Security_Frame)
        self.security_title_label.setGeometry(QtCore.QRect(250, 50, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.security_title_label.setFont(font)
        self.security_title_label.setObjectName("security_title_label")
        self.time_separator_label = QtWidgets.QLabel(self.Security_Frame)
        self.time_separator_label.setGeometry(QtCore.QRect(650, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_separator_label.setFont(font)
        self.time_separator_label.setObjectName("time_separator_label")
        self.am_pm_label = QtWidgets.QLabel(self.Security_Frame)
        self.am_pm_label.setGeometry(QtCore.QRect(700, 30, 31, 21))
        self.am_pm_label.setObjectName("am_pm_label")
        self.date_label = QtWidgets.QLabel(self.Security_Frame)
        self.date_label.setGeometry(QtCore.QRect(630, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.date_label.setFont(font)
        self.date_label.setInputMethodHints(QtCore.Qt.ImhDate)
        self.date_label.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.date_label.setObjectName("date_label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Security_Frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 220, 171, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.video_feed_widget_lable = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.video_feed_widget_lable.setFont(font)
        self.video_feed_widget_lable.setObjectName("video_feed_widget_lable")
        self.verticalLayout_3.addWidget(self.video_feed_widget_lable, 0, QtCore.Qt.AlignHCenter)
        self.play_video_label = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.play_video_label.setObjectName("play_video_label")
        self.verticalLayout_3.addWidget(self.play_video_label)
        self.video_room_selector = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.video_room_selector.setFont(font)
        self.video_room_selector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.video_room_selector.setAcceptDrops(True)
        self.video_room_selector.setFrame(True)
        self.video_room_selector.setObjectName("video_room_selector")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.video_room_selector.addItem("")
        self.verticalLayout_3.addWidget(self.video_room_selector)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Security_Frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(120, 110, 491, 107))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.arm_away_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.arm_away_button.setObjectName("arm_away_button")
        self.horizontalLayout_3.addWidget(self.arm_away_button)
        self.arm_stay_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.arm_stay_button.setObjectName("arm_stay_button")
        self.horizontalLayout_3.addWidget(self.arm_stay_button)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Security_Frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(440, 220, 171, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.entry_control_widget_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.entry_control_widget_label.setFont(font)
        self.entry_control_widget_label.setObjectName("entry_control_widget_label")
        self.verticalLayout_4.addWidget(self.entry_control_widget_label, 0, QtCore.Qt.AlignHCenter)
        self.door_lock_button_box = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_3)
        self.door_lock_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Open)
        self.door_lock_button_box.setCenterButtons(True)
        self.door_lock_button_box.setObjectName("door_lock_button_box")
        self.verticalLayout_4.addWidget(self.door_lock_button_box)
        self.entry_selector = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.entry_selector.setFont(font)
        self.entry_selector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.entry_selector.setAcceptDrops(True)
        self.entry_selector.setFrame(True)
        self.entry_selector.setObjectName("entry_selector")
        self.entry_selector.addItem("")
        self.entry_selector.addItem("")
        self.entry_selector.addItem("")
        self.entry_selector.addItem("")
        self.entry_selector.addItem("")
        self.verticalLayout_4.addWidget(self.entry_selector)
        self.back_button.raise_()
        self.minutes_label.raise_()
        self.hour_label.raise_()
        self.security_title_label.raise_()
        self.time_separator_label.raise_()
        self.date_label.raise_()
        self.am_pm_label.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.verticalLayoutWidget_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.back_button.setText(_translate("Form", "🔙"))
        self.security_title_label.setText(_translate("Form", "Security"))
        self.time_separator_label.setText(_translate("Form", ":"))
        self.am_pm_label.setText(_translate("Form", "AM"))
        self.date_label.setText(_translate("Form", "mm/dd/year"))
        self.video_feed_widget_lable.setText(_translate("Form", "Video Feed"))
        self.play_video_label.setText(_translate("Form", "Play Feed"))
        self.video_room_selector.setCurrentText(_translate("Form", "Master"))
        self.video_room_selector.setItemText(0, _translate("Form", "Master"))
        self.video_room_selector.setItemText(1, _translate("Form", "Bedroom1"))
        self.video_room_selector.setItemText(2, _translate("Form", "Bedroom2"))
        self.video_room_selector.setItemText(3, _translate("Form", "Living"))
        self.video_room_selector.setItemText(4, _translate("Form", "Family"))
        self.video_room_selector.setItemText(5, _translate("Form", "Guest"))
        self.video_room_selector.setItemText(6, _translate("Form", "Kitchen"))
        self.video_room_selector.setItemText(7, _translate("Form", "Dining"))
        self.video_room_selector.setItemText(8, _translate("Form", "Game"))
        self.video_room_selector.setItemText(9, _translate("Form", "Bathroom 1"))
        self.video_room_selector.setItemText(10, _translate("Form", "Bathroom 2"))
        self.video_room_selector.setItemText(11, _translate("Form", "Basement"))
        self.video_room_selector.setItemText(12, _translate("Form", "Library"))
        self.video_room_selector.setItemText(13, _translate("Form", "Gym"))
        self.video_room_selector.setItemText(14, _translate("Form", "Storage"))
        self.video_room_selector.setItemText(15, _translate("Form", "Garage"))
        self.arm_away_button.setText(_translate("Form", "Arm/Away"))
        self.arm_stay_button.setText(_translate("Form", "Arm/Stay"))
        self.entry_control_widget_label.setText(_translate("Form", "Entry Control"))
        self.entry_selector.setCurrentText(_translate("Form", "Whole House"))
        self.entry_selector.setItemText(0, _translate("Form", "Whole House"))
        self.entry_selector.setItemText(1, _translate("Form", "Main Entrance Door"))
        self.entry_selector.setItemText(2, _translate("Form", "Kitchen Door"))
        self.entry_selector.setItemText(3, _translate("Form", "Master Bedroom Door"))
        self.entry_selector.setItemText(4, _translate("Form", "Garage Door"))
