# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(749, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(749, 391))
        Form.setMaximumSize(QtCore.QSize(749, 391))
        Form.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(True)
        Form.setTabletTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(True)
        Form.setAutoFillBackground(True)
        self.Settings_Frame = QtWidgets.QFrame(Form)
        self.Settings_Frame.setGeometry(QtCore.QRect(0, 0, 749, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Settings_Frame.sizePolicy().hasHeightForWidth())
        self.Settings_Frame.setSizePolicy(sizePolicy)
        self.Settings_Frame.setAutoFillBackground(False)
        self.Settings_Frame.setStyleSheet("background-color: rgb(16, 128, 128);")
        self.Settings_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Settings_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Settings_Frame.setLineWidth(0)
        self.Settings_Frame.setObjectName("Settings_Frame")
        self.minutes_label = QtWidgets.QLCDNumber(self.Settings_Frame)
        self.minutes_label.setGeometry(QtCore.QRect(660, 10, 41, 41))
        self.minutes_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"fill-color: rgb(0, 0, 0);")
        self.minutes_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.minutes_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minutes_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minutes_label.setDigitCount(2)
        self.minutes_label.setProperty("intValue", 88)
        self.minutes_label.setObjectName("minutes_label")
        self.hour_label = QtWidgets.QLCDNumber(self.Settings_Frame)
        self.hour_label.setGeometry(QtCore.QRect(610, 10, 41, 41))
        self.hour_label.setAutoFillBackground(False)
        self.hour_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hour_label.setInputMethodHints(QtCore.Qt.ImhTime)
        self.hour_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hour_label.setDigitCount(2)
        self.hour_label.setProperty("intValue", 88)
        self.hour_label.setObjectName("hour_label")
        self.ambient_screen_title_label = QtWidgets.QLabel(self.Settings_Frame)
        self.ambient_screen_title_label.setGeometry(QtCore.QRect(250, 20, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.ambient_screen_title_label.setFont(font)
        self.ambient_screen_title_label.setAutoFillBackground(False)
        self.ambient_screen_title_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.ambient_screen_title_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ambient_screen_title_label.setLineWidth(0)
        self.ambient_screen_title_label.setScaledContents(False)
        self.ambient_screen_title_label.setObjectName("ambient_screen_title_label")
        self.time_separator_label = QtWidgets.QLabel(self.Settings_Frame)
        self.time_separator_label.setGeometry(QtCore.QRect(650, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_separator_label.setFont(font)
        self.time_separator_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.time_separator_label.setObjectName("time_separator_label")
        self.am_pm_label = QtWidgets.QLabel(self.Settings_Frame)
        self.am_pm_label.setGeometry(QtCore.QRect(700, 30, 31, 21))
        self.am_pm_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.am_pm_label.setObjectName("am_pm_label")
        self.date_label = QtWidgets.QLabel(self.Settings_Frame)
        self.date_label.setGeometry(QtCore.QRect(630, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.date_label.setInputMethodHints(QtCore.Qt.ImhDate)
        self.date_label.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.date_label.setObjectName("date_label")
        self.back_button = QtWidgets.QPushButton(self.Settings_Frame)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet("")
        self.back_button.setAutoDefault(False)
        self.back_button.setDefault(True)
        self.back_button.setObjectName("back_button")
        self.label = QtWidgets.QLabel(self.Settings_Frame)
        self.label.setGeometry(QtCore.QRect(560, 370, 191, 21))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")
        self.open_log_commandLinkButton = QtWidgets.QCommandLinkButton(self.Settings_Frame)
        self.open_log_commandLinkButton.setGeometry(QtCore.QRect(110, 210, 521, 46))
        self.open_log_commandLinkButton.setAutoFillBackground(False)
        self.open_log_commandLinkButton.setStyleSheet("background-color: rgba(255, 255, 255, 124);")
        self.open_log_commandLinkButton.setDefault(True)
        self.open_log_commandLinkButton.setObjectName("open_log_commandLinkButton")
        self.layoutWidget = QtWidgets.QWidget(self.Settings_Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 130, 519, 79))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.set_password_label = QtWidgets.QLabel(self.layoutWidget)
        self.set_password_label.setEnabled(True)
        self.set_password_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.set_password_label.setLineWidth(0)
        self.set_password_label.setObjectName("set_password_label")
        self.horizontalLayout.addWidget(self.set_password_label)
        self.password_spinBox_1 = QtWidgets.QSpinBox(self.layoutWidget)
        self.password_spinBox_1.setAutoFillBackground(False)
        self.password_spinBox_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.password_spinBox_1.setObjectName("password_spinBox_1")
        self.horizontalLayout.addWidget(self.password_spinBox_1)
        self.password_spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.password_spinBox_2.setAutoFillBackground(False)
        self.password_spinBox_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.password_spinBox_2.setObjectName("password_spinBox_2")
        self.horizontalLayout.addWidget(self.password_spinBox_2)
        self.password_spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.password_spinBox_3.setAutoFillBackground(False)
        self.password_spinBox_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.password_spinBox_3.setObjectName("password_spinBox_3")
        self.horizontalLayout.addWidget(self.password_spinBox_3)
        self.password_spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget)
        self.password_spinBox_4.setAutoFillBackground(False)
        self.password_spinBox_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.password_spinBox_4.setObjectName("password_spinBox_4")
        self.horizontalLayout.addWidget(self.password_spinBox_4)
        self.minutes_label.raise_()
        self.hour_label.raise_()
        self.ambient_screen_title_label.raise_()
        self.time_separator_label.raise_()
        self.date_label.raise_()
        self.am_pm_label.raise_()
        self.back_button.raise_()
        self.label.raise_()
        self.open_log_commandLinkButton.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ambient_screen_title_label.setText(_translate("Form", "Settings"))
        self.time_separator_label.setText(_translate("Form", ":"))
        self.am_pm_label.setText(_translate("Form", "AM"))
        self.date_label.setText(_translate("Form", "mm/dd/year"))
        self.back_button.setText(_translate("Form", "🔙"))
        self.label.setText(_translate("Form", "AutoHome Application(1.0.0)"))
        self.open_log_commandLinkButton.setText(_translate("Form", "Open Home Activity Log"))
        self.set_password_label.setText(_translate("Form", "Set Password:"))
